//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace adsk.ts.job.collection.user.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("adsk.ts.job.collection.user.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] Add_Generic_16_dark {
            get {
                object obj = ResourceManager.GetObject("Add_Generic_16_dark", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] Add_Generic_16_light {
            get {
                object obj = ResourceManager.GetObject("Add_Generic_16_light", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] AddToList_16_dark {
            get {
                object obj = ResourceManager.GetObject("AddToList_16_dark", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] AddToList_16_light {
            get {
                object obj = ResourceManager.GetObject("AddToList_16_light", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] Admin_16_dark {
            get {
                object obj = ResourceManager.GetObject("Admin_16_dark", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] Admin_16_light {
            get {
                object obj = ResourceManager.GetObject("Admin_16_light", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] AdminOptionsImage_16_dark {
            get {
                object obj = ResourceManager.GetObject("AdminOptionsImage_16_dark", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] AdminOptionsImage_16_light {
            get {
                object obj = ResourceManager.GetObject("AdminOptionsImage_16_light", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create 2D DWG from Inventor drawing.
        /// </summary>
        internal static string adsk_ts_acad_dwg2d_create_inventor {
            get {
                return ResourceManager.GetString("adsk.ts.acad.dwg2d.create.inventor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create 3D DWG from Inventor model.
        /// </summary>
        internal static string adsk_ts_export3d_create_inventor {
            get {
                return ResourceManager.GetString("adsk.ts.export3d.create.inventor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create image from Inventor model.
        /// </summary>
        internal static string adsk_ts_image_create_inventor {
            get {
                return ResourceManager.GetString("adsk.ts.image.create.inventor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create NWD from any CAD file.
        /// </summary>
        internal static string adsk_ts_nwd_create_navisworks {
            get {
                return ResourceManager.GetString("adsk.ts.nwd.create.navisworks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create PDF from Solidworks drawing.
        /// </summary>
        internal static string adsk_ts_pdf_create_slddrw {
            get {
                return ResourceManager.GetString("adsk.ts.pdf.create.slddrw", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create RVT from Inventor model.
        /// </summary>
        internal static string adsk_ts_rvt_create_inventor {
            get {
                return ResourceManager.GetString("adsk.ts.rvt.create.inventor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] ArrowDown_16_dark {
            get {
                object obj = ResourceManager.GetObject("ArrowDown_16_dark", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] ArrowDown_16_light {
            get {
                object obj = ResourceManager.GetObject("ArrowDown_16_light", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] ArrowUp_16_dark {
            get {
                object obj = ResourceManager.GetObject("ArrowUp_16_dark", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] ArrowUp_16_light {
            get {
                object obj = ResourceManager.GetObject("ArrowUp_16_light", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to None.
        /// </summary>
        internal static string None {
            get {
                return ResourceManager.GetString("None", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] Remove_Generic_16_dark {
            get {
                object obj = ResourceManager.GetObject("Remove Generic_16_dark", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] Remove_Generic_16_light {
            get {
                object obj = ResourceManager.GetObject("Remove Generic_16_light", resourceCulture);
                return ((byte[])(obj));
            }
        }
    }
}
